### ISSUE TITLE
Articles/Edit action does not work

### ISSUE THREAD

**Issue by hiromi2424** [gothinkster/cakephp-realworld-example-app#1]
### Env
- OS: OS X EI Capitan 10.11.6（15G1421）
- PHP: PHP 7.0.15 (cli) (built: Jan 22 2017 00:52:27) ( NTS )
- DB: MySQL Ver 14.14 Distrib 5.5.18, for osx10.6 (i386) using readline 5.1

### Front
Angular2
https://github.com/gothinkster/angular-realworld-example-app

### What's happen

Following validation error occurs

```json
{
    "error": {
        "id": "This field cannot be left empty"
    }
}
```

![2017-05-05 18 25 46](https://cloud.githubusercontent.com/assets/191297/25740276/d3f44332-31c0-11e7-83a6-ee27792cfc8f.png)

**Comment by skie** [comment]
Can you show the data that posted to the API in this case? Does the issue reproduced in postman for you?

**Comment by hiromi2424** [comment]
Following json request was logged.

```json
{"article":{"title":"ttt","slug":"ttt","description":"ttt","body":"ttt","tagList":["ccc"],"createdAt":"2017-05-05T09:17:39.000Z","updatedAt":"2017-05-05T09:17:39.000Z","author":{"username":"hiromi","bio":null,"image":null,"following":false},"favorited":0,"favoritesCount":0}}
```

**Comment by hiromi2424** [comment]
Also it is reproduced with postman(with authorization token).

![2017-05-06 09 22 17](https://cloud.githubusercontent.com/assets/191297/25768345/897cc2de-323d-11e7-8cb4-6e136aaffd6f.png)
