### ISSUE TITLE
SQLSTATE[HY000] [1045] Access denied

### ISSUE THREAD

**Issue by aikiteresa** [gothinkster/cakephp-realworld-example-app#5]
`bin/cake migrations migrate` gives 'There was a problem connecting to the database: SQLSTATE[HY000] [1045] Access denied for user 'my_app'@'localhost' (using password: YES) in [/home/aoeu/aoeu.com/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/MysqlAdapter.php, line 115] ...' error

**Comment by skie** [comment]
You must configure database in app.php before run migrations
